
export const perfis = [
    // Tema: Personagem
    {
        theme: 'Personagem',
        name: 'Homer Simpson',
        questions: [
            "Dica 1: Ele é amarelo.",
            "Dica 2: Ele gosta de donuts.",
            "Dica 3: Ele trabalha em uma usina nuclear.",
            "Dica 4: Ele tem uma esposa chamada Marge.",
            "Dica 5: Ele é pai de três filhos.",
            "Dica 6: Ele adora cerveja Duff.",
            "Dica 7: Ele vive em Springfield.",
            "Dica 8: Ele tem um vizinho chamado Ned Flanders.",
            "Dica 9: Ele costuma dizer 'D'oh!'",
            "Dica 10: Ele é um personagem de uma série animada.",
            "Dica 11: Ele tem um filho chamado Bart.",
            "Dica 12: Ele tem uma filha chamada Lisa.",
            "Dica 13: Ele tem uma filha bebê chamada Maggie.",
            "Dica 14: Ele trabalha para o Sr. Burns.",
            "Dica 15: Ele é meio preguiçoso.",
            "Dica 16: Ele adora assistir TV.",
            "Dica 17: Ele tem um cachorro chamado Santa's Little Helper.",
            "Dica 18: Ele tem um gato chamado Snowball.",
            "Dica 19: Ele tem um amigo chamado Barney.",
            "Dica 20: Ele é o protagonista de 'Os Simpsons'.",
        ],
    },
    {
        theme: 'Personagem',
        name: 'Mickey Mouse',
        questions: [
            "Dica 1: Ele é um rato.",
            "Dica 2: Ele foi criado por Walt Disney.",
            "Dica 3: Ele tem uma namorada chamada Minnie.",
            "Dica 4: Ele usa luvas brancas.",
            "Dica 5: Ele tem um amigo chamado Pateta.",
            "Dica 6: Ele tem um cachorro chamado Pluto.",
            "Dica 7: Ele foi criado em 1928.",
            "Dica 8: Ele é o mascote da Disney.",
            "Dica 9: Ele aparece em muitos filmes e séries animadas.",
            "Dica 10: Ele tem orelhas grandes e redondas.",
            "Dica 11: Ele é preto com shorts vermelhos.",
            "Dica 12: Ele é conhecido por sua voz aguda.",
            "Dica 13: Ele estrela no programa 'Clube do Mickey'.",
            "Dica 14: Ele já foi um mascote de propaganda.",
            "Dica 15: Ele apareceu pela primeira vez no curta 'Steamboat Willie'.",
            "Dica 16: Ele é muito popular entre crianças.",
            "Dica 17: Ele tem muitos produtos com sua imagem.",
            "Dica 18: Ele tem um parque temático em sua homenagem.",
            "Dica 19: Ele é conhecido mundialmente.",
            "Dica 20: Ele frequentemente diz 'Oh boy!'",
        ],
    },
    // Adicione mais personagens aqui...
    {
        theme: 'Personagem',
        name: 'Sherlock Holmes',
        questions: [
            "Dica 1: Ele é um detetive famoso.",
            "Dica 2: Ele foi criado por Arthur Conan Doyle.",
            "Dica 3: Ele mora na Baker Street.",
            "Dica 4: Seu amigo fiel é o Dr. Watson.",
            "Dica 5: Ele usa um chapéu deerstalker.",
            "Dica 6: Ele é conhecido por sua habilidade de dedução.",
            "Dica 7: Ele toca violino.",
            "Dica 8: Ele usa uma lupa para examinar pistas.",
            "Dica 9: Ele fuma cachimbo.",
            "Dica 10: Ele apareceu pela primeira vez em 'Um Estudo em Vermelho'.",
            "Dica 11: Ele tem um arqui-inimigo chamado Moriarty.",
            "Dica 12: Ele vive na Londres vitoriana.",
            "Dica 13: Ele é frequentemente retratado usando um sobretudo.",
            "Dica 14: Ele é extremamente observador.",
            "Dica 15: Ele resolve crimes complexos.",
            "Dica 16: Ele não tem muita paciência para incompetência.",
            "Dica 17: Ele usa métodos científicos para resolver casos.",
            "Dica 18: Ele é uma figura literária icônica.",
            "Dica 19: Ele foi adaptado para muitos filmes e séries.",
            "Dica 20: Ele diz frequentemente 'Elementar, meu caro Watson!'",
        ],
    },
    // Adicione mais personagens aqui...

    // Tema: Lugar
    {
        theme: 'Lugar',
        name: 'Paris',
        questions: [
            "Dica 1: É a capital da França.",
            "Dica 2: É conhecida como a 'Cidade das Luzes'.",
            "Dica 3: É famosa pela Torre Eiffel.",
            "Dica 4: Tem o Museu do Louvre.",
            "Dica 5: É conhecida pelo Rio Sena.",
            "Dica 6: Tem a Catedral de Notre-Dame.",
            "Dica 7: É famosa por sua culinária e cafés.",
            "Dica 8: Tem o Arco do Triunfo.",
            "Dica 9: É um destino turístico popular.",
            "Dica 10: Tem muitos parques e jardins bonitos.",
            "Dica 11: É conhecida pela moda e boutiques de luxo.",
            "Dica 12: Sediou a Exposição Universal de 1889.",
            "Dica 13: Tem a avenida Champs-Élysées.",
            "Dica 14: É uma cidade com muita história.",
            "Dica 15: É famosa por seus vinhos e queijos.",
            "Dica 16: Tem o bairro artístico de Montmartre.",
            "Dica 17: É conhecida por seus bistrôs.",
            "Dica 18: É a sede de muitas organizações internacionais.",
            "Dica 19: Tem uma excelente rede de transporte público.",
            "Dica 20: É uma das cidades mais românticas do mundo.",
        ],
    },
    {
        theme: 'Lugar',
        name: 'Nova York',
        questions: [
            "Dica 1: É uma cidade dos Estados Unidos.",
            "Dica 2: É conhecida como a 'Big Apple'.",
            "Dica 3: Tem a Estátua da Liberdade.",
            "Dica 4: Tem o Central Park.",
            "Dica 5: É famosa por Times Square.",
            "Dica 6: Tem a Broadway, famosa por seus teatros.",
            "Dica 7: Tem o Empire State Building.",
            "Dica 8: É um centro financeiro global.",
            "Dica 9: Tem o bairro do Brooklyn.",
            "Dica 10: É conhecida pela Ponte do Brooklyn.",
            "Dica 11: Tem o Museu Metropolitano de Arte.",
            "Dica 12: É uma cidade muito multicultural.",
            "Dica 13: Tem Wall Street.",
            "Dica 14: É um destino popular para compras.",
            "Dica 15: Tem muitos arranha-céus famosos.",
            "Dica 16: É um importante centro de moda.",
            "Dica 17: Tem uma vibrante vida noturna.",
            "Dica 18: Sediou o 9/11 Memorial.",
            "Dica 19: Tem muitas universidades renomadas.",
            "Dica 20: É o lar de muitas empresas de mídia.",
        ],
    },
    // Adicione mais lugares aqui...
    {
        theme: 'Lugar',
        name: 'Tóquio',
        questions: [
            "Dica 1: É a capital do Japão.",
            "Dica 2: É uma das cidades mais populosas do mundo.",
            "Dica 3: Tem a Torre de Tóquio.",
            "Dica 4: É famosa pelo cruzamento de Shibuya.",
            "Dica 5: Tem o Templo Senso-ji.",
            "Dica 6: É um centro de tecnologia avançada.",
            "Dica 7: Tem muitos restaurantes de sushi.",
            "Dica 8: Tem o Palácio Imperial.",
            "Dica 9: É conhecida por seus arranha-céus modernos.",
            "Dica 10: Tem muitas lojas e centros comerciais.",
            "Dica 11: Tem uma excelente rede de transporte público.",
            "Dica 12: É famosa por sua cultura pop, como anime e manga.",
            "Dica 13: Tem o Parque Ueno.",
            "Dica 14: Sedia o bairro de Akihabara, famoso por eletrônicos.",
            "Dica 15: Tem muitas áreas verdes e parques.",
            "Dica 16: É um importante centro financeiro global.",
            "Dica 17: Tem muitas casas de chá tradicionais.",
            "Dica 18: É um destino turístico popular.",
            "Dica 19: Tem o Mercado de Peixes de Tsukiji.",
            "Dica 20: É conhecida por suas cerejeiras em flor.",
        ],
    },
    // Adicione mais lugares aqui...

    // Tema: Pessoa
    {
        theme: 'Pessoa',
        name: 'Albert Einstein',
        questions: [
            "Dica 1: Ele era um físico teórico.",
            "Dica 2: Ele desenvolveu a teoria da relatividade.",
            "Dica 3: Ele nasceu na Alemanha.",
            "Dica 4: Ele ganhou o Prêmio Nobel de Física em 1921.",
            "Dica 5: Ele é famoso por sua equação E=mc².",
            "Dica 6: Ele tinha um cabelo característico.",
            "Dica 7: Ele emigrou para os EUA em 1933.",
            "Dica 8: Ele trabalhou no Instituto de Estudos Avançados em Princeton.",
            "Dica 9: Ele foi um pacifista convicto.",
            "Dica 10: Ele contribuiu para o desenvolvimento da mecânica quântica.",
            "Dica 11: Ele era conhecido por sua curiosidade e criatividade.",
            "Dica 12: Ele publicou mais de 300 artigos científicos.",
            "Dica 13: Ele ajudou a fundar a Universidade Hebraica de Jerusalém.",
            "Dica 14: Ele tinha uma forte aversão ao nacionalismo.",
            "Dica 15: Ele é frequentemente associado à imagem de um 'gênio'.",
            "Dica 16: Ele apoiou o movimento pelos direitos civis nos EUA.",
            "Dica 17: Ele era um crítico do sistema educacional tradicional.",
            "Dica 18: Ele escreveu muitos livros populares sobre ciência.",
            "Dica 19: Ele recebeu cidadania suíça em 1901.",
            "Dica 20: Ele morreu em 1955.",
        ],
    },
    {
        theme: 'Pessoa',
        name: 'Marie Curie',
        questions: [
            "Dica 1: Ela foi uma cientista famosa.",
            "Dica 2: Ela nasceu na Polônia.",
            "Dica 3: Ela ganhou dois Prêmios Nobel.",
            "Dica 4: Ela descobriu os elementos rádio e polônio.",
            "Dica 5: Ela foi a primeira mulher a ganhar um Prêmio Nobel.",
            "Dica 6: Ela trabalhou com radiação.",
            "Dica 7: Ela foi a primeira mulher a ser professora na Universidade de Paris.",
            "Dica 8: Ela fundou o Instituto Curie em Paris.",
            "Dica 9: Ela trabalhou durante a Primeira Guerra Mundial em radiologia móvel.",
            "Dica 10: Ela teve duas filhas, uma das quais também ganhou um Prêmio Nobel.",
            "Dica 11: Ela recebeu sua educação inicial em Varsóvia.",
            "Dica 12: Ela enfrentou muitos desafios em sua carreira devido ao seu gênero.",
            "Dica 13: Ela morreu de anemia aplástica.",
            "Dica 14: Ela é um ícone na história das mulheres na ciência.",
            "Dica 15: Ela foi a primeira pessoa a ganhar Prêmios Nobel em duas ciências diferentes.",
            "Dica 16: Ela estudou na Sorbonne em Paris.",
            "Dica 17: Ela casou-se com o cientista Pierre Curie.",
            "Dica 18: Ela usava laboratórios improvisados no início de sua carreira.",
            "Dica 19: Ela recebeu reconhecimento postumamente com muitos institutos e prêmios em seu nome.",
            "Dica 20: Ela foi pioneira no estudo da radioatividade.",
        ],
    },
    // Adicione mais pessoas aqui...
    {
        theme: 'Pessoa',
        name: 'Nelson Mandela',
        questions: [
            "Dica 1: Ele foi o primeiro presidente negro da África do Sul.",
            "Dica 2: Ele passou 27 anos na prisão.",
            "Dica 3: Ele lutou contra o apartheid.",
            "Dica 4: Ele ganhou o Prêmio Nobel da Paz em 1993.",
            "Dica 5: Ele nasceu em Mvezo, África do Sul.",
            "Dica 6: Ele foi advogado.",
            "Dica 7: Ele foi membro do Congresso Nacional Africano.",
            "Dica 8: Ele é conhecido por sua política de reconciliação.",
            "Dica 9: Ele publicou uma autobiografia chamada 'Long Walk to Freedom'.",
            "Dica 10: Ele foi libertado da prisão em 1990.",
            "Dica 11: Ele morreu em 2013.",
            "Dica 12: Ele foi um ícone global da luta pelos direitos humanos.",
            "Dica 13: Ele tinha o apelido de 'Madiba'.",
            "Dica 14: Ele foi casado três vezes.",
            "Dica 15: Ele foi o líder da ala militar do ANC.",
            "Dica 16: Ele estudou na Universidade de Fort Hare.",
            "Dica 17: Ele ajudou a estabelecer a democracia multirracial na África do Sul.",
            "Dica 18: Ele foi um defensor da paz e da justiça social.",
            "Dica 19: Ele teve um papel fundamental na criação da nova constituição da África do Sul.",
            "Dica 20: Ele é lembrado como um símbolo de resistência e esperança.",
        ],
    },
    // Adicione mais pessoas aqui...

    // Tema: Coisa
    {
        theme: 'Coisa',
        name: 'Computador',
        questions: [
            "Dica 1: É uma máquina eletrônica.",
            "Dica 2: É usado para processar informações.",
            "Dica 3: Tem uma unidade central de processamento (CPU).",
            "Dica 4: Pode armazenar dados.",
            "Dica 5: Usa um sistema operacional.",
            "Dica 6: Pode ser de mesa ou portátil.",
            "Dica 7: Tem memória RAM.",
            "Dica 8: Pode conectar-se à internet.",
            "Dica 9: Pode ser usado para jogar jogos.",
            "Dica 10: É essencial em escritórios modernos.",
            "Dica 11: Pode executar software de produtividade.",
            "Dica 12: Pode ser usado para programação.",
            "Dica 13: Tem dispositivos de entrada como teclado e mouse.",
            "Dica 14: Pode ser usado para edição de vídeo.",
            "Dica 15: Tem uma tela para exibir informações.",
            "Dica 16: Pode ser conectado a impressoras.",
            "Dica 17: É usado em educação.",
            "Dica 18: Pode ser usado para design gráfico.",
            "Dica 19: Pode executar aplicativos de música.",
            "Dica 20: É usado para comunicação.",
        ],
    },
    {
        theme: 'Coisa',
        name: 'Smartphone',
        questions: [
            "Dica 1: É um dispositivo portátil.",
            "Dica 2: Pode fazer chamadas telefônicas.",
            "Dica 3: Tem uma tela sensível ao toque.",
            "Dica 4: Pode acessar a internet.",
            "Dica 5: Tem uma câmera integrada.",
            "Dica 6: Pode executar aplicativos.",
            "Dica 7: Tem capacidade de GPS.",
            "Dica 8: Pode enviar mensagens de texto.",
            "Dica 9: Pode armazenar música e vídeos.",
            "Dica 10: Usa uma bateria recarregável.",
            "Dica 11: Tem um sistema operacional como iOS ou Android.",
            "Dica 12: Pode ser usado para redes sociais.",
            "Dica 13: Tem capacidade de Wi-Fi.",
            "Dica 14: Pode ser usado para navegação na web.",
            "Dica 15: Tem armazenamento interno.",
            "Dica 16: Pode ser usado para pagar contas.",
            "Dica 17: Tem um processador interno.",
            "Dica 18: Pode ser usado para jogos.",
            "Dica 19: Pode ser sincronizado com outros dispositivos.",
            "Dica 20: Pode ser personalizado com capas e acessórios.",
        ],
    },
    // Adicione mais coisas aqui...
    {
        theme: 'Coisa',
        name: 'Bicicleta',
        questions: [
            "Dica 1: Tem duas rodas.",
            "Dica 2: É usada para transporte.",
            "Dica 3: Pode ser usada para exercícios.",
            "Dica 4: É movida pela força humana.",
            "Dica 5: Tem um guidão.",
            "Dica 6: Tem pedais.",
            "Dica 7: Pode ter marchas.",
            "Dica 8: Pode ser usada em ciclovias.",
            "Dica 9: Tem freios.",
            "Dica 10: Pode ter uma campainha.",
            "Dica 11: Pode ter uma cesta.",
            "Dica 12: É usada em competições de ciclismo.",
            "Dica 13: Pode ter luzes para segurança.",
            "Dica 14: É uma alternativa ecológica ao carro.",
            "Dica 15: Pode ser dobrável.",
            "Dica 16: Pode ter amortecedores.",
            "Dica 17: Pode ter suportes para garrafas.",
            "Dica 18: É usada em mountain bike.",
            "Dica 19: Pode ter um selim ajustável.",


            "Dica 20: Pode ser personalizada com acessórios.",
        ],
    },

    {
      theme: 'Filme',
      name: 'Titanic',
      questions: [
          "Dica 1: É um filme dirigido por James Cameron.",
          "Dica 2: É baseado em um evento real de um navio famoso.",
          "Dica 3: Tem Leonardo DiCaprio como protagonista.",
          "Dica 4: É conhecido pela música 'My Heart Will Go On'.",
          "Dica 5: Ganhou vários Oscars.",
          "Dica 6: Foi lançado em 1997.",
          "Dica 7: Tem uma cena icônica na proa do navio.",
          "Dica 8: Tem Kate Winslet como protagonista feminina.",
          "Dica 9: É um dos filmes de maior bilheteria de todos os tempos.",
          "Dica 10: É uma história de romance e tragédia.",
          "Dica 11: Tem o naufrágio do RMS Titanic como pano de fundo.",
          "Dica 12: Foi filmado em locações reais e em estúdios.",
          "Dica 13: Tem uma versão em 3D lançada em 2012.",
          "Dica 14: É conhecido por seus efeitos visuais inovadores.",
          "Dica 15: Tem uma cena famosa de dança na terceira classe do navio.",
          "Dica 16: É frequentemente reprisado na televisão.",
          "Dica 17: Tem uma narrativa que mistura ficção com fatos históricos.",
          "Dica 18: Tem Billy Zane como um dos antagonistas.",
          "Dica 19: Tem uma cena dramática com uma porta flutuante.",
          "Dica 20: Tem uma cena emocionante de despedida no final.",
      ],
  },
  {
      theme: 'Filme',
      name: 'Matrix',
      questions: [
          "Dica 1: É um filme de ficção científica.",
          "Dica 2: Tem Keanu Reeves como protagonista.",
          "Dica 3: É dirigido pelos irmãos Wachowski.",
          "Dica 4: É conhecido pela 'Matrix Reloaded' e 'Matrix Revolutions'.",
          "Dica 5: Foi lançado em 1999.",
          "Dica 6: Explora temas de realidade virtual e controle da mente.",
          "Dica 7: Tem uma cena famosa de esquiva de balas.",
          "Dica 8: Introduziu o conceito de 'Matrix' como uma simulação digital.",
          "Dica 9: Tem Laurence Fishburne como Morpheus.",
          "Dica 10: Tem uma trilha sonora marcante e efeitos visuais inovadores.",
          "Dica 11: É um marco no gênero de ficção científica dos anos 90.",
          "Dica 12: Tem uma cena de treinamento com o personagem Neo.",
          "Dica 13: Explora filosofias sobre realidade e livre arbítrio.",
          "Dica 14: É o primeiro filme de uma trilogia.",
          "Dica 15: Tem uma cena de luta coreografada de forma única.",
          "Dica 16: Ganhou Oscars por seus efeitos visuais.",
          "Dica 17: Tem um enredo que questiona a natureza da existência humana.",
          "Dica 18: É conhecido por seus diálogos filosóficos.",
          "Dica 19: Tem Carrie-Anne Moss como Trinity.",
          "Dica 20: Teve um impacto duradouro na cultura pop.",
      ],
  },
  // Adicione mais filmes aqui...
  
  // Tema: Música
  {
      theme: 'Música',
      name: 'Michael Jackson',
      questions: [
          "Dica 1: Ele foi um famoso cantor e dançarino.",
          "Dica 2: É conhecido como o 'Rei do Pop'.",
          "Dica 3: Ele lançou o álbum 'Thriller', um dos mais vendidos de todos os tempos.",
          "Dica 4: Ele tinha um passo de dança chamado 'Moonwalk'.",
          "Dica 5: Ele começou sua carreira no grupo Jackson 5.",
          "Dica 6: Ele teve uma carreira solo de grande sucesso.",
          "Dica 7: Ele era conhecido por seu estilo visual único.",
          "Dica 8: Ele ganhou vários prêmios Grammy.",
          "Dica 9: Ele era um fenômeno global de música pop.",
          "Dica 10: Ele teve uma série de hits como 'Billie Jean' e 'Beat It'.",
          "Dica 11: Ele tinha uma voz distintiva e uma presença de palco carismática.",
          "Dica 12: Ele foi um ícone cultural dos anos 80 e 90.",
          "Dica 13: Ele foi envolvido em causas de caridade.",
          "Dica 14: Ele era conhecido por sua vida pessoal controversa.",
          "Dica 15: Ele era um artista multifacetado, também atuando e dançando.",
          "Dica 16: Ele tinha fãs em todo o mundo.",
          "Dica 17: Ele morreu em 2009.",
          "Dica 18: Ele foi introduzido no Rock and Roll Hall of Fame duas vezes.",
          "Dica 19: Ele foi um dos artistas mais vendidos de todos os tempos.",
          "Dica 20: Ele era um inovador na indústria da música.",
      ],
  },
  {
      theme: 'Música',
      name: 'Adele',
      questions: [
          "Dica 1: Ela é uma cantora britânica.",
          "Dica 2: Ela ganhou vários prêmios Grammy.",
          "Dica 3: Ela é conhecida por suas baladas emocionais.",
          "Dica 4: Ela lançou o álbum '21', um dos mais vendidos da década.",
          "Dica 5: Ela teve hits como 'Rolling in the Deep' e 'Someone Like You'.",
          "Dica 6: Ela começou sua carreira na adolescência.",
          "Dica 7: Ela é conhecida por sua voz poderosa.",
          "Dica 8: Ela é uma das artistas mais populares do século XXI.",
          "Dica 9: Ela teve uma residência de sucesso em Las Vegas.",
          "Dica 10: Ela lançou o álbum '25', seguido de '30'.",
          "Dica 11: Ela é conhecida por suas letras pessoais e introspectivas.",
          "Dica 12: Ela é uma das artistas mais premiadas da sua geração.",
          "Dica 13: Ela é uma figura influente na música pop contemporânea.",
          "Dica 14: Ela é conhecida por sua discrição na vida pessoal.",
          "Dica 15: Ela tem milhões de fãs ao redor do mundo.",
          "Dica 16: Ela ganhou um Oscar pela música 'Skyfall'.",
          "Dica 17: Ela fez um hiato de carreira antes de retornar com sucesso.",
          "Dica 18: Ela é uma das artistas mais vendidas da história.",
          "Dica 19: Ela recebeu um MBE por serviços à música.",
          "Dica 20: Ela é conhecida por seu talento vocal e emocional.",
      ],
  },
  {
    theme: 'Personagem',
    name: 'Harry Potter',
    questions: [
        "Dica 1: Ele é um bruxo.",
        "Dica 2: Ele estudou em Hogwarts.",
        "Dica 3: Ele tem uma cicatriz em forma de raio na testa.",
        "Dica 4: Ele é conhecido por derrotar Lord Voldemort.",
        "Dica 5: Ele é amigo de Ron Weasley e Hermione Granger.",
        "Dica 6: Ele tem uma coruja chamada Edwiges.",
        "Dica 7: Ele é da casa Grifinória.",
        "Dica 8: Ele usa uma varinha de teixo e pena de fênix.",
        "Dica 9: Ele é conhecido por sua habilidade em voo de vassoura.",
        "Dica 10: Ele é o personagem principal de uma série de livros e filmes.",
        "Dica 11: Ele é conhecido por sua bondade e coragem.",
        "Dica 12: Ele é órfão e foi criado pelos tios que não gostam de magia.",
        "Dica 13: Ele é uma figura icônica na cultura pop.",
        "Dica 14: Ele tem pais que foram bruxos famosos.",
        "Dica 15: Ele é um dos melhores jogadores de quadribol da Grifinória.",
        "Dica 16: Ele foi capitão da equipe de quadribol da Grifinória.",
        "Dica 17: Ele tem habilidades únicas em feitiçaria.",
        "Dica 18: Ele é conhecido por seu senso de justiça.",
        "Dica 19: Ele tem uma habilidade rara de falar a língua das cobras.",
        "Dica 20: Ele é conhecido por seu patrono, que é um cervo."
    ],
},
{
    theme: 'Personagem',
    name: 'Spider-Man (Homem-Aranha)',
    questions: [
        "Dica 1: Ele é um super-herói.",
        "Dica 2: Ele foi picado por uma aranha radioativa.",
        "Dica 3: Ele é conhecido por sua agilidade e força sobre-humana.",
        "Dica 4: Ele é fotógrafo e trabalha para o Clarim Diário.",
        "Dica 5: Ele vive em Nova York.",
        "Dica 6: Ele é alter-ego de Peter Parker.",
        "Dica 7: Ele tem um tio chamado Ben, cuja morte o inspirou a lutar contra o crime.",
        "Dica 8: Ele tem uma tia chamada May.",
        "Dica 9: Ele é um dos fundadores dos Vingadores.",
        "Dica 10: Ele é conhecido por suas tiradas durante os combates.",
        "Dica 11: Ele usa um traje azul e vermelho com teias.",
        "Dica 12: Ele é conhecido por enfrentar inimigos como Duende Verde e Doutor Octopus.",
        "Dica 13: Ele é membro dos Defensores.",
        "Dica 14: Ele é conhecido por sua inteligência e inventividade.",
        "Dica 15: Ele é um dos super-heróis mais queridos da Marvel Comics.",
        "Dica 16: Ele é um ávido fã de ciência.",
        "Dica 17: Ele é conhecido por seus conflitos com o simbionte Venom.",
        "Dica 18: Ele é amigo de super-heróis como Homem de Ferro e Capitão América.",
        "Dica 19: Ele é conhecido por sua compaixão e senso de responsabilidade.",
        "Dica 20: Ele é frequentemente retratado como um adolescente ou jovem adulto."
    ],
},
{
    theme: 'Lugar',
    name: 'Rio de Janeiro',
    questions: [
        "Dica 1: É uma cidade do Brasil.",
        "Dica 2: É conhecida como a 'Cidade Maravilhosa'.",
        "Dica 3: Tem o Cristo Redentor.",
        "Dica 4: Tem o Pão de Açúcar.",
        "Dica 5: É famosa pelas praias de Copacabana e Ipanema.",
        "Dica 6: Tem o Carnaval do Rio de Janeiro.",
        "Dica 7: Tem o Maracanã, um dos maiores estádios de futebol do mundo.",
        "Dica 8: É conhecida por sua música e dança, como o samba e o funk carioca.",
        "Dica 9: Tem o Jardim Botânico.",
        "Dica 10: Tem o Museu de Arte Moderna (MAM).",
        "Dica 11: É um importante centro cultural e econômico do Brasil.",
        "Dica 12: Tem uma rica história colonial.",
        "Dica 13: É conhecida por sua paisagem montanhosa e oceânica.",
        "Dica 14: É um destino turístico popular tanto para brasileiros quanto estrangeiros.",
        "Dica 15: Tem uma das maiores festas de Réveillon do mundo em Copacabana.",
        "Dica 16: É sede de muitos eventos internacionais, como a Rio+20 e as Olimpíadas de 2016.",
        "Dica 17: É conhecida por sua diversidade cultural e religiosa.",
        "Dica 18: Tem uma das maiores favelas do Brasil, Rocinha.",
        "Dica 19: É conhecida pela sua gastronomia, incluindo pratos como a feijoada e o acarajé.",
        "Dica 20: É um importante centro de moda e design no Brasil."
    ],
},
{
    theme: 'Lugar',
    name: 'Taj Mahal',
    questions: [
        "Dica 1: É um mausoléu.",
        "Dica 2: Está localizado em Agra, Índia.",
        "Dica 3: Foi construído pelo imperador Shah Jahan.",
        "Dica 4: É conhecido por sua beleza arquitetônica.",
        "Dica 5: Foi construído em memória da esposa favorita do imperador, Mumtaz Mahal.",
        "Dica 6: É feito de mármore branco.",
        "Dica 7: É um Patrimônio Mundial da UNESCO.",
        "Dica 8: É um símbolo do amor eterno.",
        "Dica 9: É uma das Sete Maravilhas do Mundo Moderno.",
        "Dica 10: Foi concluído em 1653.",
        "Dica 11: Tem jardins simétricos ao redor do mausoléu.",
        "Dica 12: É um destino turístico muito popular na Índia.",
        "Dica 13: É iluminado durante a lua cheia à noite.",
        "Dica 14: É um exemplo da arquitetura mogol.",
        "Dica 15: É visitado por milhões de pessoas todos os anos.",
        "Dica 16: É um símbolo de riqueza e luxo no período do Império Mogol.",
        "Dica 17: É um local de grande importância histórica e cultural na Índia.",
        "Dica 18: É retratado em muitas obras de arte e fotografias.",
        "Dica 19: É um testemunho do talento dos artesãos e arquitetos da época.",
        "Dica 20: É uma atração turística que atrai visitantes de todo o mundo."
    ],
},

{
  theme: 'Pessoa',
  name: 'Albert Einstein',
  questions: [
      "Dica 1: Ele foi um físico teórico.",
      "Dica 2: Ele é famoso pela teoria da relatividade.",
      "Dica 3: Ele ganhou o Prêmio Nobel de Física em 1921.",
      "Dica 4: Ele nasceu na Alemanha e emigrou para os Estados Unidos durante a Segunda Guerra Mundial.",
      "Dica 5: Ele é conhecido por sua equação E=mc².",
      "Dica 6: Ele era um defensor do pacifismo e dos direitos civis.",
      "Dica 7: Ele trabalhou no Instituto de Estudos Avançados em Princeton.",
      "Dica 8: Ele teve contribuições significativas para a mecânica quântica e a cosmologia.",
      "Dica 9: Ele era conhecido por seu cabelo desalinhado e aparência distinta.",
      "Dica 10: Ele era um violinista amador e gostava de música clássica.",
      "Dica 11: Ele era um crítico fervoroso do nazismo e do militarismo.",
      "Dica 12: Ele desenvolveu teorias sobre o movimento browniano e o efeito fotoelétrico.",
      "Dica 13: Ele era um pensador profundo sobre a natureza do tempo e do espaço.",
      "Dica 14: Ele é um dos cientistas mais famosos da história.",
      "Dica 15: Ele influenciou profundamente o desenvolvimento da física moderna.",
      "Dica 16: Ele era um humanista e defendia ideais de justiça social.",
      "Dica 17: Ele deixou um legado duradouro na ciência e na cultura popular.",
      "Dica 18: Ele é frequentemente citado por suas frases memoráveis sobre a vida, o universo e tudo mais.",
      "Dica 19: Ele era conhecido por sua capacidade de simplificar conceitos complexos da física para o público em geral.",
      "Dica 20: Ele é admirado não apenas por suas descobertas científicas, mas também por sua integridade moral e ética."
  ],
},
{
  theme: 'Coisa',
  name: 'Câmera Fotográfica',
  questions: [
      "Dica 1: É um dispositivo para capturar imagens.",
      "Dica 2: Funciona com filme ou digitalmente.",
      "Dica 3: Tem um botão de disparo.",
      "Dica 4: Usa lentes para focar a luz.",
      "Dica 5: É usado por fotógrafos profissionais e amadores.",
      "Dica 6: Tem controles para ajustar a exposição, abertura e velocidade do obturador.",
      "Dica 7: Pode ser encontrada em vários tamanhos e formatos.",
      "Dica 8: Evoluiu ao longo dos anos desde as câmeras de filme até as digitais.",
      "Dica 9: É essencial para capturar momentos especiais e registrar eventos históricos.",
      "Dica 10: Pode ser encontrada em modelos compactos, DSLRs e câmeras mirrorless.",
      "Dica 11: É usada em diversas áreas, como jornalismo, arte, ciência e documentação.",
      "Dica 12: Tem sido uma ferramenta importante na preservação da história visual.",
      "Dica 13: Pode ser usada para criar arte fotográfica e expressar criatividade.",
      "Dica 14: É parte integrante da indústria cinematográfica para filmagens.",
      "Dica 15: Tem sido influenciada por avanços tecnológicos como autofoco e estabilização de imagem.",
      "Dica 16: É usada para capturar paisagens, retratos, vida selvagem e eventos esportivos.",
      "Dica 17: Pode ser usada com diferentes tipos de acessórios, como flashes e tripés.",
      "Dica 18: É um meio poderoso de comunicação visual.",
      "Dica 19: É usada para criar memórias pessoais e históricas.",
      "Dica 20: É uma ferramenta essencial para profissionais e entusiastas da fotografia."
  ],
},
{
  theme: 'Coisa',
  name: 'Helicóptero',
  questions: [
      "Dica 1: É uma aeronave.",
      "Dica 2: Pode decolar e pousar verticalmente.",
      "Dica 3: Tem hélices que proporcionam sustentação e propulsão.",
      "Dica 4: Pode voar para frente, para trás e para os lados.",
      "Dica 5: É usado para transporte pessoal, militar e de emergência.",
      "Dica 6: Tem um rotor principal e, às vezes, um rotor de cauda.",
      "Dica 7: Pode transportar passageiros e carga.",
      "Dica 8: Pode ser usado para resgate em áreas de difícil acesso.",
      "Dica 9: É usado para filmagem aérea e monitoramento.",
      "Dica 10: É usado para combater incêndios e apoiar operações de segurança pública.",
      "Dica 11: É usado em missões de busca e salvamento.",
      "Dica 12: Pode ser equipado com tecnologia avançada, como câmeras infravermelhas e sistemas de navegação GPS.",
      "Dica 13: É uma forma eficiente de transporte em áreas urbanas e rurais.",
      "Dica 14: É usado para transporte executivo e turismo.",
      "Dica 15: É um dos meios mais versáteis de transporte aéreo.",
      "Dica 16: Pode operar em condições meteorológicas variadas.",
      "Dica 17: É usado em operações militares para apoio logístico e de combate.",
      "Dica 18: É usado em plataformas offshore para transporte de pessoal e suprimentos.",
      "Dica 19: É um símbolo de inovação na aviação.",
      "Dica 20: Tem sido usado em operações humanitárias para entregar ajuda em áreas afetadas por desastres."
  ],
},
{
  theme: 'Marca',
  name: 'Coca-Cola',
  questions: [
      "Dica 1: É uma bebida carbonatada.",
      "Dica 2: Foi criada em 1886 nos Estados Unidos.",
      "Dica 3: É conhecida por sua cor vermelha distintiva e logotipo.",
      "Dica 4: É uma das marcas mais reconhecidas globalmente.",
      "Dica 5: Tem uma fórmula secreta de sabor.",
      "Dica 6: É vendida em garrafas de vidro, latas e garrafas de plástico.",
      "Dica 7: É consumida em todo o mundo.",
      "Dica 8: Tem uma variedade de versões, incluindo Coca-Cola Clássica e Diet Coke.",
      "Dica 9: É frequentemente servida com gelo e limão.",
      "Dica 10: É uma das marcas mais valiosas do mundo.",
      "Dica 11: Tem sido um símbolo de cultura pop e estilo de vida.",
      "Dica 12: É patrocinadora de eventos esportivos e culturais globalmente.",
      "Dica 13: É uma das bebidas mais consumidas em festas e celebrações.",
      "Dica 14: É uma das principais rivais da PepsiCo.",
      "Dica 15: Tem sido objeto de muitas campanhas publicitárias icônicas ao longo dos anos.",
      "Dica 16: Tem sido associada a momentos de felicidade e celebração.",
      "Dica 17: É um símbolo de refrescância e prazer.",
      "Dica 18: Tem uma presença significativa nas redes sociais e plataformas digitais.",
      "Dica 19: É frequentemente consumida com hambúrgueres e pizza.",
      "Dica 20: É uma marca que transcende gerações e culturas."
  ],
},
{
  theme: 'Marca',
  name: 'Apple Inc.',
  questions: [
      "Dica 1: É uma empresa de tecnologia.",
      "Dica 2: Foi fundada por Steve Jobs, Steve Wozniak e Ronald Wayne.",
      "Dica 3: É conhecida por produtos como iPhone, iPad, MacBook e Apple Watch.",
      "Dica 4: Tem sede em Cupertino, Califórnia, Estados Unidos.",
      "Dica 5: É uma das empresas mais valiosas do mundo.",
      "Dica 6: Tem uma forte reputação de design e inovação.",
      "Dica 7: Lançou o primeiro computador pessoal com interface gráfica, o Macintosh.",
      "Dica 8: Desenvolveu o sistema operacional iOS.",
      "Dica 9: Tem uma loja de aplicativos chamada App Store.",
      "Dica 10: É conhecida por suas campanhas publicitárias minimalistas e impactantes.",
      "Dica 11: É uma das principais empresas do setor de tecnologia de consumo.",
      "Dica 12: Tem uma base de fãs leais e entusiastas de seus produtos.",
      "Dica 13: É conhecida por sua abordagem integrada de hardware, software e serviços.",
      "Dica 14: É uma líder em sustentabilidade e responsabilidade social corporativa.",
      "Dica 15: Lançou o iTunes, revolucionando a distribuição de música digital.",
      "Dica 16: É uma marca aspiracional associada à criatividade e produtividade.",
      "Dica 17: É uma das empresas mais inovadoras da última década.",
      "Dica 18: Tem sido um modelo de sucesso empresarial e liderança visionária.",
      "Dica 19: É conhecida por suas lojas de varejo com design distinto.",
      "Dica 20: Tem uma história de transformar indústrias e moldar o futuro da tecnologia."
  ],
},
{
  theme: 'Coisa',
  name: 'Raquete de Tênis',
  questions: [
      "Dica 1: É usada em um esporte de raquete.",
      "Dica 2: Tem uma superfície de cordas.",
      "Dica 3: É usada para bater uma bola.",
      "Dica 4: É comum em quadras de tênis.",
      "Dica 5: Pode ter diferentes tamanhos e pesos.",
      "Dica 6: Pode ter uma estrutura de grafite ou alumínio.",
      "Dica 7: É usada para realizar golpes como saque e voleio.",
      "Dica 8: Tem um cabo para segurar.",
      "Dica 9: Pode ser utilizada tanto em quadras de grama quanto de saibro.",
      "Dica 10: É uma peça essencial no tênis de campo.",
      "Dica 11: Possui uma cabeça onde ficam as cordas.",
      "Dica 12: É usada para bater na bola durante o jogo.",
      "Dica 13: Pode ter raquetes específicas para crianças.",
      "Dica 14: É frequentemente personalizada com grip.",
      "Dica 15: Pode ter uma capa para proteção.",
      "Dica 16: As cordas podem ser de vários materiais, como nylon ou tripa natural.",
      "Dica 17: Existem raquetes para diferentes estilos de jogo.",
      "Dica 18: Usada por jogadores como Rafael Nadal e Roger Federer.",
      "Dica 19: Pode ser encontrada em diferentes cores e designs.",
      "Dica 20: É uma das principais peças no tênis de mesa.",
  ],
},

{
  theme: 'Coisa',
  name: 'Pipoca',
  questions: [
      "Dica 1: É um lanche comum em cinemas.",
      "Dica 2: É feita de milho.",
      "Dica 3: Fica estourada quando aquecida.",
      "Dica 4: Pode ser temperada com sal ou manteiga.",
      "Dica 5: É um snack popular em festas.",
      "Dica 6: É crocante e leve.",
      "Dica 7: Pode ser doce ou salgada.",
      "Dica 8: É feita em uma panela ou micro-ondas.",
      "Dica 9: Pode ser servida em tigelas grandes.",
      "Dica 10: É um dos alimentos mais simples e deliciosos.",
      "Dica 11: É um snack que agrada a adultos e crianças.",
      "Dica 12: Pode ser comprada já pronta ou feita em casa.",
      "Dica 13: Muitas vezes é acompanhada de refrigerante.",
      "Dica 14: É rica em fibras.",
      "Dica 15: É um dos primeiros alimentos a serem estourados.",
      "Dica 16: É um acompanhamento popular para filmes.",
      "Dica 17: É deliciosa quando temperada com queijo.",
      "Dica 18: Pode ser encontrada em diversas formas, como doce ou salgada.",
      "Dica 19: É frequentemente usada em festivais e eventos.",
      "Dica 20: É uma guloseima fácil de preparar.",
  ],
},

{
  theme: 'Coisa',
  name: 'Skate',
  questions: [
      "Dica 1: É um esporte de rua.",
      "Dica 2: Tem quatro rodas.",
      "Dica 3: É usado para deslizar em rampas e pistas.",
      "Dica 4: Pode ter diferentes tipos de shapes.",
      "Dica 5: É comum em parques e nas ruas.",
      "Dica 6: Pode ter trucks de diferentes tamanhos.",
      "Dica 7: É usado para realizar manobras.",
      "Dica 8: Pode ser de madeira ou plástico.",
      "Dica 9: É um meio de transporte alternativo.",
      "Dica 10: É popular entre jovens.",
      "Dica 11: Pode ter diferentes tipos de rodas, dependendo da superfície.",
      "Dica 12: Skate parks são locais comuns para prática.",
      "Dica 13: É usado para fazer tricks como ollies e kickflips.",
      "Dica 14: É comum ver skatistas usando tênis específicos.",
      "Dica 15: É um esporte radical.",
      "Dica 16: Pode ter shapes com diferentes designs e cores.",
      "Dica 17: É conhecido por sua cultura de estilo de vida.",
      "Dica 18: É um esporte olímpico.",
      "Dica 19: Skatistas famosos incluem Tony Hawk e Bob Burnquist.",
      "Dica 20: É um esporte que pode ser praticado em qualquer lugar.",
  ],
},

{
  theme: 'Coisa',
  name: 'Jogo de Tabuleiro',
  questions: [
      "Dica 1: É um passatempo coletivo.",
      "Dica 2: Pode ter peças e tabuleiro.",
      "Dica 3: É jogado em família ou com amigos.",
      "Dica 4: Existem muitos tipos, como xadrez e dama.",
      "Dica 5: Pode ter dados ou cartas.",
      "Dica 6: É uma forma de entretenimento tradicional.",
      "Dica 7: Pode ser competitivo ou cooperativo.",
      "Dica 8: É popular em reuniões sociais.",
      "Dica 9: Pode envolver estratégia e sorte.",
      "Dica 10: É uma atividade que estimula o pensamento lógico.",
      "Dica 11: Pode ter regras e objetivos específicos.",
      "Dica 12: É uma ótima maneira de reunir amigos e família.",
      "Dica 13: Existem jogos de tabuleiro para todas as idades.",
      "Dica 14: Pode ser um passatempo educacional.",
      "Dica 15: Pode incluir peças como figuras e cartas.",
      "Dica 16: É conhecido por promover a interação social.",
      "Dica 17: Pode ter temas variados, como fantasia ou aventura.",
      "Dica 18: É uma alternativa divertida ao uso de eletrônicos.",
      "Dica 19: Jogos como Monopoly e Scrabble são clássicos.",
      "Dica 20: Pode ser encontrado em versões para todas as idades.",
  ],
},

{
  theme: 'Coisa',
  name: 'Trampolim',
  questions: [
      "Dica 1: É usado para saltar.",
      "Dica 2: Tem uma superfície elástica.",
      "Dica 3: É comum em parques de diversão.",
      "Dica 4: Pode ser grande ou pequeno.",
      "Dica 5: É usado para realizar acrobacias.",
      "Dica 6: Pode ser encontrado em jardins e escolas.",
      "Dica 7: Tem uma estrutura de metal ou plástico.",
      "Dica 8: É usado tanto por crianças quanto por adultos.",
      "Dica 9: Pode ser usado em treinamento de esportes.",
      "Dica 10: É divertido e saudável.",
      "Dica 11: Pode ter uma rede de proteção ao redor.",
      "Dica 12: É usado para melhorar a coordenação motora.",
      "Dica 13: Pode ser uma atividade recreativa em festas.",
      "Dica 14: É seguro quando usado corretamente.",
      "Dica 15: Pode ter diferentes tamanhos e formatos.",
      "Dica 16: É usado em competições de trampolim.",
      "Dica 17: Pode ser usado para exercícios de baixo impacto.",
      "Dica 18: É um equipamento de ginástica.",
      "Dica 19: Pode ser encontrado em academias.",
      "Dica 20: É ideal para atividades recreativas ao ar livre.",
  ],
},

{
  theme: 'Coisa',
  name: 'Escalada',
  questions: [
      "Dica 1: É um esporte de aventura.",
      "Dica 2: Pode ser indoor ou outdoor.",
      "Dica 3: Usa cordas e equipamentos de segurança.",
      "Dica 4: Pode ser em montanhas ou paredes de escalada.",
      "Dica 5: Requer força e resistência.",
      "Dica 6: É um esporte que desafia a altura.",
      "Dica 7: Usa sapatilhas especiais para aderência.",
      "Dica 8: Pode ter diferentes níveis de dificuldade.",
      "Dica 9: É popular em locais como Yosemite e Mont Blanc.",
      "Dica 10: Pode ser praticada por amadores e profissionais.",
      "Dica 11: É um esporte que exige técnica e estratégia.",
      "Dica 12: Pode envolver escalada esportiva ou tradicional.",
      "Dica 13: Usa cordas, mosquetões e cintos.",
      "Dica 14: É praticada em ambientes naturais e em centros de escalada.",
      "Dica 15: Pode ser praticada em rochas ou paredes artificiais.",
      "Dica 16: Requer treinamento físico e mental.",
      "Dica 17: É um esporte que promove a conexão com a natureza.",
      "Dica 18: Usa equipamentos de proteção individual.",
      "Dica 19: Pode ser uma atividade de grupo ou solo.",
      "Dica 20: É um esporte que exige planejamento e preparação.",
  ],
},

{
  theme: 'Coisa',
  name: 'Jogo de Tabuleiro',
  questions: [
      "Dica 1: É um passatempo coletivo.",
      "Dica 2: Pode ter peças e tabuleiro.",
      "Dica 3: É jogado em família ou com amigos.",
      "Dica 4: Existem muitos tipos, como xadrez e dama.",
      "Dica 5: Pode ter dados ou cartas.",
      "Dica 6: É uma forma de entretenimento tradicional.",
      "Dica 7: Pode ser competitivo ou cooperativo.",
      "Dica 8: É popular em reuniões sociais.",
      "Dica 9: Pode envolver estratégia e sorte.",
      "Dica 10: É uma atividade que estimula o pensamento lógico.",
      "Dica 11: Pode ter regras e objetivos específicos.",
      "Dica 12: É uma ótima maneira de reunir amigos e família.",
      "Dica 13: Existem jogos de tabuleiro para todas as idades.",
      "Dica 14: Pode ser um passatempo educacional.",
      "Dica 15: Pode incluir peças como figuras e cartas.",
      "Dica 16: É conhecido por promover a interação social.",
      "Dica 17: Pode ter temas variados, como fantasia ou aventura.",
      "Dica 18: É uma alternativa divertida ao uso de eletrônicos.",
      "Dica 19: Jogos como Monopoly e Scrabble são clássicos.",
      "Dica 20: Pode ser encontrado em versões para todas as idades.",
  ],
},

{
  theme: 'Coisa',
  name: 'Trampolim',
  questions: [
      "Dica 1: É usado para saltar.",
      "Dica 2: Tem uma superfície elástica.",
      "Dica 3: É comum em parques de diversão.",
      "Dica 4: Pode ser grande ou pequeno.",
      "Dica 5: É usado para realizar acrobacias.",
      "Dica 6: Pode ser encontrado em jardins e escolas.",
      "Dica 7: Tem uma estrutura de metal ou plástico.",
      "Dica 8: É usado tanto por crianças quanto por adultos.",
      "Dica 9: Pode ser usado em treinamento de esportes.",
      "Dica 10: É divertido e saudável.",
      "Dica 11: Pode ter uma rede de proteção ao redor.",
      "Dica 12: É usado para melhorar a coordenação motora.",
      "Dica 13: Pode ser uma atividade recreativa em festas.",
      "Dica 14: É seguro quando usado corretamente.",
      "Dica 15: Pode ter diferentes tamanhos e formatos.",
      "Dica 16: É usado em competições de trampolim.",
      "Dica 17: Pode ser usado para exercícios de baixo impacto.",
      "Dica 18: É um equipamento de ginástica.",
      "Dica 19: Pode ser encontrado em academias.",
      "Dica 20: É ideal para atividades recreativas ao ar livre.",
  ],
},

{
  theme: 'Coisa',
  name: 'Escalada',
  questions: [
      "Dica 1: É um esporte de aventura.",
      "Dica 2: Pode ser indoor ou outdoor.",
      "Dica 3: Usa cordas e equipamentos de segurança.",
      "Dica 4: Pode ser em montanhas ou paredes de escalada.",
      "Dica 5: Requer força e resistência.",
      "Dica 6: É um esporte que desafia a altura.",
      "Dica 7: Usa sapatilhas especiais para aderência.",
      "Dica 8: Pode ter diferentes níveis de dificuldade.",
      "Dica 9: É popular em locais como Yosemite e Mont Blanc.",
      "Dica 10: Pode ser praticada por amadores e profissionais.",
      "Dica 11: É um esporte que exige técnica e estratégia.",
      "Dica 12: Pode envolver escalada esportiva ou tradicional.",
      "Dica 13: Usa cordas, mosquetões e cintos.",
      "Dica 14: É praticada em ambientes naturais e em centros de escalada.",
      "Dica 15: Pode ser praticada em rochas ou paredes artificiais.",
      "Dica 16: Requer treinamento físico e mental.",
      "Dica 17: É um esporte que promove a conexão com a natureza.",
      "Dica 18: Usa equipamentos de proteção individual.",
      "Dica 19: Pode ser uma atividade de grupo ou solo.",
      "Dica 20: É um esporte que exige planejamento e preparação.",
  ],
},

{
  theme: 'Coisa',
  name: 'Piano',
  questions: [
      "Dica 1: É um instrumento musical de teclado.",
      "Dica 2: Tem teclas brancas e pretas.",
      "Dica 3: É usado para tocar música clássica e contemporânea.",
      "Dica 4: Pode ter um banco para o músico sentar.",
      "Dica 5: É comum em salas de concerto e estúdios.",
      "Dica 6: Pode ser de cauda ou vertical.",
      "Dica 7: Tem pedais para controlar o som.",
      "Dica 8: É um dos instrumentos mais populares do mundo.",
      "Dica 9: Pode ser usado como acompanhamento para cantores.",
      "Dica 10: Requer prática e habilidade para tocar bem.",
      "Dica 11: É um instrumento versátil.",
      "Dica 12: Pode ser encontrado em diferentes tamanhos.",
      "Dica 13: É usado em música erudita e popular.",
      "Dica 14: Pode ser um piano de cauda Steinway ou Yamaha.",
      "Dica 15: É um instrumento que pode ser tocado solo ou em grupo.",
      "Dica 16: Pode ser digital ou acústico.",
      "Dica 17: É um dos instrumentos mais antigos.",
      "Dica 18: Pode ser afinado regularmente.",
      "Dica 19: É usado por músicos famosos como Lang Lang e Elton John.",
      "Dica 20: É um instrumento que exige técnica e expressão.",
  ],
},

{
  theme: 'Coisa',
  name: 'Câmera Fotográfica',
  questions: [
      "Dica 1: É usada para capturar imagens.",
      "Dica 2: Tem lentes e um corpo.",
      "Dica 3: Pode ser digital ou analógica.",
      "Dica 4: É comum em fotos de família e eventos.",
      "Dica 5: Pode ter diferentes tipos de lentes.",
      "Dica 6: É usada por fotógrafos profissionais e amadores.",
      "Dica 7: Pode ter controles manuais para ajustar a exposição.",
      "Dica 8: É usada para criar memórias e registrar momentos.",
      "Dica 9: Pode ter diferentes resoluções de imagem.",
      "Dica 10: É um equipamento essencial para muitos profissionais.",
      "Dica 11: Pode ter modos automáticos para facilitar o uso.",
      "Dica 12: É usada para capturar paisagens e retratos.",
      "Dica 13: Pode ter uma tela LCD para visualização das fotos.",
      "Dica 14: Pode ser compacta ou profissional.",
      "Dica 15: É usada em jornalismo e fotografia artística.",
      "Dica 16: Pode ter uma alça para transporte.",
      "Dica 17: É usada para documentar viagens e eventos especiais.",
      "Dica 18: Pode ser encontrada em diferentes marcas, como Canon e Nikon.",
      "Dica 19: É um objeto de desejo para entusiastas da fotografia.",
      "Dica 20: É um instrumento que captura momentos únicos.",
  ],
},

{
  theme: 'Coisa',
  name: 'Patins',
  questions: [
      "Dica 1: É usado para deslizar sobre superfícies.",
      "Dica 2: Tem rodas ou lâminas.",
      "Dica 3: É usado para lazer e esporte.",
      "Dica 4: Pode ser inline ou quad.",
      "Dica 5: É comum em parques e pistas.",
      "Dica 6: Pode ter diferentes tamanhos de rodas.",
      "Dica 7: É usado para realizar manobras.",
      "Dica 8: Pode ser ajustado para diferentes tamanhos de pés.",
      "Dica 9: É um meio de transporte divertido.",
      "Dica 10: É popular entre jovens e adultos.",
      "Dica 11: Pode ser usado em competições de patinação artística.",
      "Dica 12: Pode ter freios para controle de velocidade.",
      "Dica 13: É usado para se movimentar com rapidez.",
      "Dica 14: Pode ser encontrado em diferentes estilos e cores.",
      "Dica 15: É um equipamento de proteção para o corpo.",
      "Dica 16: É um esporte que promove o equilíbrio e coordenação.",
      "Dica 17: Pode ser usado em pistas de gelo ou asfalto.",
      "Dica 18: É usado para exercícios aeróbicos.",
      "Dica 19: Patins em linha são usados para velocidade e manobras.",
      "Dica 20: É um esporte que requer prática e habilidade.",
  ],
},

{
  theme: 'Coisa',
  name: 'Lanterna',
  questions: [
      "Dica 1: É usada para iluminar áreas escuras.",
      "Dica 2: Pode ser de mão ou de cabeça.",
      "Dica 3: É comum em acampamentos e emergências.",
      "Dica 4: Usa baterias ou pilhas.",
      "Dica 5: Pode ter diferentes intensidades de luz.",
      "Dica 6: É um item de segurança em caminhadas noturnas.",
      "Dica 7: Pode ter uma alça para transporte.",
      "Dica 8: É usado por profissionais de resgate.",
      "Dica 9: Pode ter um botão para ligar e desligar.",
      "Dica 10: É essencial em kits de emergência.",
      "Dica 11: Pode ter um design resistente à água.",
      "Dica 12: É usado para explorar cavernas e ambientes fechados.",
      "Dica 13: Pode ter uma lente ajustável para foco de luz.",
      "Dica 14: É um objeto útil durante quedas de energia.",
      "Dica 15: Pode ser encontrado em diferentes tamanhos e cores.",
      "Dica 16: É usado para sinalização em situações de emergência.",
      "Dica 17: Pode ser recarregável ou descartável.",
      "Dica 18: É um item de sobrevivência.",
      "Dica 19: Pode ter uma luz LED ou incandescente.",
      "Dica 20: É um objeto prático para atividades ao ar livre.",
  ],
},

{
  theme: 'Coisa',
  name: 'Micro-ondas',
  questions: [
      "Dica 1: É usado para aquecer alimentos rapidamente.",
      "Dica 2: É comum em cozinhas domésticas.",
      "Dica 3: Usa micro-ondas para gerar calor.",
      "Dica 4: Pode ter diferentes configurações de potência.",
      "Dica 5: É usado para descongelar e cozinhar alimentos.",
      "Dica 6: Pode ter um painel de controle digital.",
      "Dica 7: É um eletrodoméstico conveniente para refeições rápidas.",
      "Dica 8: Pode ter um prato giratório para distribuir o calor.",
      "Dica 9: É encontrado em muitas casas e apartamentos.",
      "Dica 10: É usado para aquecer bebidas como café e leite.",
      "Dica 11: Pode ter funções pré-programadas para diferentes alimentos.",
      "Dica 12: É um eletrodoméstico seguro quando usado corretamente.",
      "Dica 13: Pode ter uma porta com fechamento automático.",
      "Dica 14: É um equipamento que economiza tempo na cozinha.",
      "Dica 15: Pode ter uma função de timer para controle preciso.",
      "Dica 16: É usado para preparar pipoca e alimentos congelados.",
      "Dica 17: Pode ter uma luz interna para monitorar o aquecimento.",
      "Dica 18: É um eletrodoméstico popular desde sua invenção.",
      "Dica 19: Pode ter uma função de descongelamento rápido.",
      "Dica 20: É um item essencial para cozinhas modernas.",
  ],
},

{
  theme: 'Coisa',
  name: 'Violão',
  questions: [
      "Dica 1: É um instrumento de cordas.",
      "Dica 2: Tem seis cordas.",
      "Dica 3: É usado para tocar música popular e clássica.",
      "Dica 4: Pode ter um corpo de madeira.",
      "Dica 5: É comum em apresentações ao vivo e estúdios.",
      "Dica 6: Tem trastes para notas musicais.",
      "Dica 7: É usado para acompanhar cantores e outros músicos.",
      "Dica 8: É um instrumento versátil.",
      "Dica 9: Pode ser tocado com os dedos ou com palheta.",
      "Dica 10: Requer prática para tocar bem.",
      "Dica 11: É um dos instrumentos mais populares do mundo.",
      "Dica 12: Pode ter diferentes tamanhos e formatos.",
      "Dica 13: É um instrumento usado em música folclórica.",
      "Dica 14: Pode ter cordas de aço ou nylon.",
      "Dica 15: É usado em diversos gêneros musicais.",
      "Dica 16: É um instrumento que pode ser tocado solo ou em conjunto.",
      "Dica 17: Pode ser encontrado em diferentes cores e acabamentos.",
      "Dica 18: É um instrumento que pode ser transportado facilmente.",
      "Dica 19: É usado por músicos famosos como Ed Sheeran e Taylor Swift.",
      "Dica 20: É um instrumento que combina harmonia e melodia.",
  ],
},

{
  theme: 'Coisa',
  name: 'Relógio',
  questions: [
      "Dica 1: É usado para medir o tempo.",
      "Dica 2: Pode ser analógico ou digital.",
      "Dica 3: É usado como acessório e ferramenta.",
      "Dica 4: Pode ter mostradores para horas, minutos e segundos.",
      "Dica 5: É comum em pulsos e paredes.",
      "Dica 6: Pode ter diferentes designs e materiais.",
      "Dica 7: É usado para programar atividades diárias.",
      "Dica 8: Pode ter funções como alarme e cronômetro.",
      "Dica 9: É um objeto prático e decorativo.",
      "Dica 10: Pode ter uma pulseira de couro ou metal.",
      "Dica 11: É um acessório de moda.",
      "Dica 12: Pode ser um relógio de pulso ou de parede.",
      "Dica 13: Pode ter ponteiros luminosos para visualização noturna.",
      "Dica 14: É usado em viagens para controlar fusos horários.",
      "Dica 15: Pode ser um presente elegante e útil.",
      "Dica 16: É um instrumento de precisão.",
      "Dica 17: Pode ser à prova d'água para atividades ao ar livre.",
      "Dica 18: Pode ter um calendário embutido.",
      "Dica 19: Pode ser encontrado em marcas de luxo como Rolex e Omega.",
      "Dica 20: É um item essencial no dia a dia.",
  ],
},

{
  theme: 'Coisa',
  name: 'Caixa de Ferramentas',
  questions: [
      "Dica 1: É usada para armazenar ferramentas.",
      "Dica 2: Pode ter diferentes compartimentos.",
      "Dica 3: É usada por profissionais e amadores.",
      "Dica 4: Pode ter alças para transporte.",
      "Dica 5: É comum em oficinas e garagens.",
      "Dica 6: Pode ter ferramentas como martelo e chave de fenda.",
      "Dica 7: É usada para organização e segurança de ferramentas.",
      "Dica 8: Pode ter um design resistente e durável.",
      "Dica 9: É essencial para reparos e manutenção.",
      "Dica 10: Pode ter uma bandeja removível para acessórios menores.",
      "Dica 11: É um item essencial para DIY (faça você mesmo).",
      "Dica 12: Pode ter fechos para manter as ferramentas seguras.",
      "Dica 13: Pode ser encontrada em diferentes tamanhos e materiais.",
      "Dica 14: É usada para guardar chaves e alicates.",
      "Dica 15: Pode ser uma caixa portátil ou fixa.",
      "Dica 16: É um equipamento de armazenamento prático.",
      "Dica 17: Pode ter uma tampa transparente para fácil visualização.",
      "Dica 18: É um presente útil para entusiastas de DIY.",
      "Dica 19: Pode ter um espaço para etiquetagem de ferramentas.",
      "Dica 20: É uma caixa que ajuda na organização de espaços de trabalho.",
  ],
},

{
  theme: 'Coisa',
  name: 'Bicicleta',
  questions: [
      "Dica 1: É um veículo de duas rodas.",
      "Dica 2: É usado para transporte e lazer.",
      "Dica 3: Tem pedais e guidão.",
      "Dica 4: Pode ter diferentes tipos, como mountain bike e bicicleta de estrada.",
      "Dica 5: É comum em parques e ciclovias.",
      "Dica 6: Pode ter marchas para diferentes terrenos.",
      "Dica 7: É usado para exercício físico e mobilidade urbana.",
      "Dica 8: Pode ter um quadro de alumínio ou carbono.",
      "Dica 9: É um meio de transporte ecológico.",
      "Dica 10: Pode ser usado por crianças e adultos.",
      "Dica 11: Pode ter acessórios como cestas e campainhas.",
      "Dica 12: É um transporte alternativo ao carro.",
      "Dica 13: Pode ter pneus largos para terrenos irregulares.",
      "Dica 14: É usado em competições como o Tour de France.",
      "Dica 15: Pode ter freios a disco para maior segurança.",
      "Dica 16: É um esporte olímpico.",
      "Dica 17: Pode ser personalizado com adesivos e acessórios.",
      "Dica 18: É um meio de transporte acessível.",
      "Dica 19: Pode ser dobrável para fácil armazenamento.",
      "Dica 20: É um veículo que promove um estilo de vida ativo.",
  ],
},

{
  theme: 'Coisa',
  name: 'Guarda-chuva',
  questions: [
      "Dica 1: É usado para proteger da chuva.",
      "Dica 2: Pode ser dobrável ou de tamanho grande.",
      "Dica 3: É comum em dias chuvosos.",
      "Dica 4: Pode ter um cabo de madeira ou plástico.",
      "Dica 5: É um acessório essencial em regiões úmidas.",
      "Dica 6: Pode ter uma capa para armazenamento.",
      "Dica 7: É usado para proteger contra sol e chuva.",
      "Dica 8: Pode ser encontrado em cores variadas.",
      "Dica 9: É usado por pessoas de todas as idades.",
      "Dica 10: Pode ter tecidos impermeáveis.",
      "Dica 11: Pode ser compacto para fácil transporte.",
      "Dica 12: É um item de guarda-roupa essencial.",
      "Dica 13: Pode ter um mecanismo automático de abertura.",
      "Dica 14: É usado para caminhadas e viagens.",
      "Dica 15: Pode ter uma estrutura resistente ao vento.",
      "Dica 16: É um presente útil em estações chuvosas.",
      "Dica 17: Pode ter um design elegante e funcional.",
      "Dica 18: É um acessório comum em cidades urbanas.",
      "Dica 19: Pode ser usado em dias ensolarados e chuvosos.",
      "Dica 20: É um item que proporciona conforto e praticidade.",
  ],
},

{
  theme: 'Coisa',
  name: 'Foguete',
  questions: [
      "Dica 1: É um veículo espacial.",
      "Dica 2: É usado para viagens além da atmosfera terrestre.",
      "Dica 3: Usa propulsores para alcançar a órbita.",
      "Dica 4: Pode ter estágios de lançamento.",
      "Dica 5: É um símbolo da exploração espacial.",
      "Dica 6: Pode ser tripulado ou não tripulado.",
      "Dica 7: É lançado de bases espaciais.",
      "Dica 8: Pode ser usado para lançar satélites e espaçonaves.",
      "Dica 9: É um projeto colaborativo entre países.",
      "Dica 10: Pode ter um design aerodinâmico.",
      "Dica 11: É usado para pesquisa científica e comunicações.",
      "Dica 12: Pode ser reutilizável para reduzir custos.",
      "Dica 13: É monitorado por centros de controle de missão.",
      "Dica 14: Pode ter uma cápsula para transportar astronautas.",
      "Dica 15: É um marco na história da conquista espacial.",
      "Dica 16: Pode ser usado para explorar outros planetas.",
      "Dica 17: É um exemplo de tecnologia avançada.",
      "Dica 18: Pode ter um sistema de escape de emergência.",
      "Dica 19: É lançado verticalmente.",
      "Dica 20: É um objeto de inspiração para futuras gerações.",
  ],
},

{
  theme: 'Coisa',
  name: 'Bola de Futebol',
  questions: [
      "Dica 1: É usada para jogar futebol.",
      "Dica 2: Tem um design esférico.",
      "Dica 3: É comum em campos e quadras.",
      "Dica 4: Pode ter cores e padrões variados.",
      "Dica 5: É um item essencial em partidas de futebol.",
      "Dica 6: Pode ser feita de couro ou materiais sintéticos.",
      "Dica 7: É usada por jogadores de todas as idades.",
      "Dica 8: Pode ser inflada para ajustar a pressão.",
      "Dica 9: É usada para chutes e passes durante o jogo.",
      "Dica 10: É um símbolo do esporte mais popular do mundo.",
      "Dica 11: Pode ter uma câmara interna para manter a forma.",
      "Dica 12: É usada em competições profissionais e amadoras.",
      "Dica 13: Pode ter uma superfície texturizada para controle.",
      "Dica 14: É usada em treinos e recreação.",
      "Dica 15: Pode ter um tamanho padrão ou ser mini para crianças.",
      "Dica 16: É um objeto de coleção para fãs de futebol.",
      "Dica 17: Pode ser personalizada com logotipos e marcas.",
      "Dica 18: É um item essencial em escolas e clubes esportivos.",
      "Dica 19: Pode ser encontrada em diferentes marcas esportivas.",
      "Dica 20: É uma bola que une pessoas em torno do esporte.",
  ],
},

{
  theme: 'Coisa',
  name: 'Cadeira',
  questions: [
      "Dica 1: É usada para sentar.",
      "Dica 2: Pode ter um encosto e assento.",
      "Dica 3: É comum em mesas e salas.",
      "Dica 4: Pode ter diferentes designs e materiais.",
      "Dica 5: É um móvel essencial em casas e escritórios.",
      "Dica 6: Pode ter braços para apoio.",
      "Dica 7: É usada para conforto e descanso.",
      "Dica 8: Pode ser ajustável em altura.",
      "Dica 9: É encontrada em cores variadas.",
      "Dica 10: Pode ter rodízios para movimentação.",
      "Dica 11: Pode ser ergonômica para suporte postural.",
      "Dica 12: É um item de mobília que proporciona conforto.",
      "Dica 13: Pode ter estofamento para maciez.",
      "Dica 14: É usada em refeições e trabalho.",
      "Dica 15: Pode ter um design moderno ou clássico.",
      "Dica 16: É um item de decoração em ambientes.",
      "Dica 17: Pode ter um apoio lombar.",
      "Dica 18: É usada para hospedar visitantes.",
      "Dica 19: Pode ser dobrável para armazenamento.",
      "Dica 20: É uma cadeira que proporciona conforto e estilo.",
  ],
},

{
  theme: 'Coisa',
  name: 'Guitarra',
  questions: [
      "Dica 1: É um instrumento de cordas.",
      "Dica 2: Tem seis cordas.",
      "Dica 3: É usada para tocar rock, blues e outros estilos musicais.",
      "Dica 4: Pode ter um corpo sólido ou semi-acústico.",
      "Dica 5: É comum em bandas e performances ao vivo.",
      "Dica 6: Tem trastes para notas musicais.",
      "Dica 7: É usada para solos e acompanhamentos.",
      "Dica 8: É um instrumento versátil.",
      "Dica 9: Pode ser tocada com os dedos ou com palheta.",
      "Dica 10: Requer prática para tocar bem.",
      "Dica 11: É um dos instrumentos mais populares do mundo.",
      "Dica 12: Pode ter diferentes acabamentos e designs.",
      "Dica 13: É um instrumento usado em música contemporânea.",
      "Dica 14: Pode ter captadores para amplificar o som.",
      "Dica 15: É usado em diversos gêneros musicais.",
      "Dica 16: É um instrumento que pode ser tocado solo ou em conjunto.",
      "Dica 17: Pode ser encontrado em modelos elétricos e acústicos.",
      "Dica 18: É um instrumento que pode ser personalizado com adesivos.",
      "Dica 19: É usado por músicos famosos como Jimi Hendrix e Eric Clapton.",
      "Dica 20: É um instrumento que combina ritmo e melodia.",
  ],
},

{
  theme: 'Coisa',
  name: 'Espelho',
  questions: [
      "Dica 1: É usado para refletir imagens.",
      "Dica 2: Pode ter um moldura decorativa.",
      "Dica 3: É comum em banheiros e quartos.",
      "Dica 4: Pode ter diferentes formas e tamanhos.",
      "Dica 5: É usado para verificar a aparência pessoal.",
      "Dica 6: Pode ter uma superfície plana ou convexa.",
      "Dica 7: É um item essencial em vestiários e salões de beleza.",
      "Dica 8: Pode ser montado em paredes ou móveis.",
      "Dica 9: É encontrado em casas e estabelecimentos comerciais.",
      "Dica 10: Pode ter uma luz embutida para iluminação adicional.",
      "Dica 11: É usado para maquiagem e cuidados com a pele.",
      "Dica 12: Pode ser um espelho de corpo inteiro.",
      "Dica 13: É usado para verificar o estilo e a roupa.",
      "Dica 14: Pode ter um revestimento antiembaçante.",
      "Dica 15: É um item de decoração em ambientes.",
      "Dica 16: Pode ser ajustável para diferentes ângulos.",
      "Dica 17: É usado para refletir luz em espaços escuros.",
      "Dica 18: Pode ter um design moderno ou vintage.",
      "Dica 19: É um objeto que facilita a preparação pessoal.",
      "Dica 20: É um espelho que reflete estilo e funcionalidade.",
  ],
},

{
  theme: 'Personagem',
  name: 'Batman',
  questions: [
      "Dica 1: Ele é conhecido como o Cavaleiro das Trevas.",
      "Dica 2: Ele protege Gotham City.",
      "Dica 3: Ele não tem superpoderes, mas é um detetive habilidoso.",
      "Dica 4: Ele é alter ego de Bruce Wayne, um bilionário.",
      "Dica 5: Ele é acompanhado por seu parceiro Robin em suas aventuras.",
      "Dica 6: Ele tem uma galeria de vilões famosos como o Coringa e o Charada.",
      "Dica 7: Ele usa um uniforme preto e um símbolo de morcego no peito.",
      "Dica 8: Ele dirige o Batmóvel, um carro altamente tecnológico.",
      "Dica 9: Ele treinou suas habilidades físicas e mentais para combater o crime.",
      "Dica 10: Ele é um dos membros fundadores da Liga da Justiça.",
      "Dica 11: Ele tem uma relação complexa com a Mulher-Gato, uma anti-heroína.",
      "Dica 12: Ele é conhecido por seu código de ética rígido contra matar.",
      "Dica 13: Ele tem uma mansão chamada Wayne Manor.",
      "Dica 14: Ele é um dos personagens mais icônicos da DC Comics.",
      "Dica 15: Ele usa dispositivos como o Batarang para combater o crime.",
      "Dica 16: Ele é mestre em artes marciais e estratégia de combate.",
      "Dica 17: Ele é retratado em várias adaptações de filmes e séries de TV.",
      "Dica 18: Ele é um símbolo de justiça e vigilância.",
      "Dica 19: Ele enfrenta seus próprios demônios internos enquanto protege a cidade.",
      "Dica 20: Ele é conhecido por dizer 'Eu sou o Batman'.",
  ],
},
{
  theme: 'Personagem',
  name: 'Sonic the Hedgehog',
  questions: [
      "Dica 1: Ele é um ouriço azul.",
      "Dica 2: Ele é conhecido por sua velocidade supersônica.",
      "Dica 3: Ele é o mascote da Sega.",
      "Dica 4: Ele tem um amigo chamado Tails.",
      "Dica 5: Ele enfrenta o Dr. Robotnik, seu arqui-inimigo.",
      "Dica 6: Ele é rápido como um raio.",
      "Dica 7: Ele coleta anéis de ouro em suas aventuras.",
      "Dica 8: Ele estrela em jogos de plataforma.",
      "Dica 9: Ele é um dos personagens mais reconhecidos dos videogames.",
      "Dica 10: Ele tem uma série de desenhos animados.",
      "Dica 11: Ele é conhecido por seu estilo de vida aventureiro e corajoso.",
      "Dica 12: Ele é muito ágil e pode correr em círculos ao redor de seus inimigos.",
      "Dica 13: Ele é uma espécie de ouriço antropomórfico.",
      "Dica 14: Ele é amigo de outros animais antropomórficos.",
      "Dica 15: Ele é retratado como um herói que protege seu mundo de ameaças.",
      "Dica 16: Ele foi criado para competir com o personagem Mario da Nintendo.",
      "Dica 17: Ele tem uma série de histórias em quadrinhos.",
      "Dica 18: Ele é muito popular entre crianças e adultos.",
      "Dica 19: Ele foi adaptado para vários produtos de merchandising.",
      "Dica 20: Ele é um ícone da cultura pop dos anos 90 até hoje.",
  ],
},
{
  theme: 'Personagem',
  name: 'Darth Vader',
  questions: [
      "Dica 1: Ele é um dos vilões mais icônicos de todos os tempos.",
      "Dica 2: Ele é um Lorde Sith do lado negro da Força.",
      "Dica 3: Ele é pai de Luke Skywalker e Leia Organa.",
      "Dica 4: Ele usa uma máscara e uma capa negra.",
      "Dica 5: Ele é interpretado por David Prowse fisicamente e por James Earl Jones vocalmente.",
      "Dica 6: Ele é o aprendiz do Imperador Palpatine.",
      "Dica 7: Ele foi um Jedi antes de se voltar para o lado negro.",
      "Dica 8: Ele é conhecido por sua respiração mecânica pesada.",
      "Dica 9: Ele comanda as tropas imperiais e os temidos Stormtroopers.",
      "Dica 10: Ele é mestre em combate com um sabre de luz vermelho.",
      "Dica 11: Ele é uma figura trágica com um passado complexo.",
      "Dica 12: Ele é uma das figuras centrais na saga 'Star Wars'.",
      "Dica 13: Ele é conhecido por dizer 'Eu sou seu pai'.",
      "Dica 14: Ele é implacável na busca pelo poder absoluto.",
      "Dica 15: Ele tem uma presença imponente e intimidadora.",
      "Dica 16: Ele é uma das figuras mais reconhecíveis da cultura pop.",
      "Dica 17: Ele é um símbolo de conflito interno e redenção.",
      "Dica 18: Ele tem uma história expandida em livros, quadrinhos e filmes.",
      "Dica 19: Ele é admirado por sua habilidade estratégica e tática.",
      "Dica 20: Ele é uma das maiores criações de George Lucas.",
  ],
},
{
  theme: 'Personagem',
  name: 'Sherlock Holmes',
  questions: [
      "Dica 1: Ele é um detetive famoso.",
      "Dica 2: Ele foi criado por Arthur Conan Doyle.",
      "Dica 3: Ele mora na Baker Street.",
      "Dica 4: Seu amigo fiel é o Dr. Watson.",
      "Dica 5: Ele usa um chapéu deerstalker.",
      "Dica 6: Ele é conhecido por sua habilidade de dedução.",
      "Dica 7: Ele toca violino.",
      "Dica 8: Ele usa uma lupa para examinar pistas.",
      "Dica 9: Ele fuma cachimbo.",
      "Dica 10: Ele apareceu pela primeira vez em 'Um Estudo em Vermelho'.",
      "Dica 11: Ele tem um arqui-inimigo chamado Moriarty.",
      "Dica 12: Ele vive na Londres vitoriana.",
      "Dica 13: Ele é frequentemente retratado usando um sobretudo.",
      "Dica 14: Ele é extremamente observador.",
      "Dica 15: Ele resolve crimes complexos.",
      "Dica 16: Ele não tem muita paciência para incompetência.",
      "Dica 17: Ele usa métodos científicos para resolver casos.",
      "Dica 18: Ele é uma figura literária icônica.",
      "Dica 19: Ele foi adaptado para muitos filmes e séries.",
      "Dica 20: Ele diz frequentemente 'Elementar, meu caro Watson!'",
  ],
},
  // Ad
    // Adicione mais coisas aqui...
];